#include "apple.h"

//copies the position generated by the game into the apple object
Apple::Apple(Position position){
    this->position = position;
}

//returns the apple position so the game can detect when the snake eats it
Position Apple::getPosition(){
    return position;
}
